### ISSUE TITLE
Update for Vapor 2.0

### ISSUE THREAD

**Issue by torrao** [vapor-community/forms#12]
Hi,

Vapor 2.0 is currently out of beta, are you planning to update this to support it?

Many thanks in advance

**Comment by bygri** [comment]
Hi @torrao. Yes, I am. I cannot make any promises about when I will be finished with the work, however. New baby at home takes up most of my energy at present. Sorry about that.

**Comment by calebkleveter** [comment]
Bump.

**Comment by vzsg** [comment]
Resolved in [1.0.0 Beta 1](https://github.com/vapor-community/forms/releases/tag/1.0.0-beta.1).
